server:
  port: 8081

spring:
  cloud:
    function:
      definition: listen
    stream:
      bindings:
        listen-in-0: # functionName-in-0 (in per input, out per output)
          group: ${CONSUMER_GROUP_NAME:dummy-group}
          destination: image-topic # topic name
          content-type: image/png # content-type of the message
      kafka:
        binder:
          auto-create-topics: true
          min-partition-count: 1
          brokers: ${KAFKA_BROKERS:localhost:9092} # broker address, you can put multiple and separate them with a coma


